keys:
  - &failsafe age1hvcusdalp5x58m8lmm39hah3qpcmr4fac587yjz4qukcfuhdafmqchsc5f
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *failsafe
